### ISSUE TITLE
Release 0.1.0 task list

### ISSUE THREAD

**Issue by voytech** [voytech/tabulate#134]
- [x] Enhance README 
- [x] Documentation coverage
- [ ] Generic typing correctness + declaration site variance + reducing unchecked casts
- [x] mergeWith -> overrideWith
- [ ] Generic <T> with upper bounds like :  T : Any ?  
- [ ] #141
- [x] RenderingContext - is it needed ?
- [x] #135
- [x] #137
- [x] #136
- [x] attributes.takeIfChanged, isModified should be protected.
- [ ] make sealed classes where applicable
- [ ]  Either for ColumnKey? 
- [ ] inline functions.
- [x] Internal modifiers should be almost everywhere!
- [x] #144
- [x] ExportOperation - beginRow should , renderRowCell - revisit contract
- [x] #140
- [x]  #116
- [ ] #69
- [ ] #24
- [x] #60
- [ ] Replace attribute merge with plus op
- [ ] Consider 'RequiresOptIn' annotations for AttributedExportOperations in order to use more specialised interface which should be hidden by default.
- [x] #145
- [x] AttributeExportOperationFactory should be resolved also if it is comptible for given RenderingContext subclass.
- [ ] #147
- [x] #148
